general:
steps:
  mtaBuild:
    buildTarget: 'CF'
    npmExecuteLint: true

  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: 'a004cb52trial'
      space: 'dev'
      credentialsId: 'CF_IDENTITY_FOR_JENKINS'
  
  whitesourceExecuteScan:
    projectNames: 'CloudFoundryJava'
    stashContent:
      - 'source'    